modif gha des testsÃ

diff --git a/.github/workflows/R-pkg-testing.yaml b/.github/workflows/R-pkg-testing.yaml
--- a/.github/workflows/R-pkg-testing.yaml
+++ b/.github/workflows/R-pkg-testing.yaml
@@ -40,3 +40,12 @@ jobs:
       - name: Run tests
         run: devtools::test()
         shell: Rscript {0}
+
+      - name: Check test results
+        run: |
+          # Check if any test files have failed
+          if [ -n "$(find results/testthat -type f -name '*-failed.Rout')" ]; then
+            echo "Tests have failed"
+            exit 1
+          fi
+        shell: bash
